In [2]:
#np.random.rand, np.max(), np.sin(), np.exp(), np.log()

import numpy as np

In [3]:
arr_2nd = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [4]:
arr_2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr_2nd[2,1]

40

In [6]:
arr_2nd[0][1]

10

In [7]:
arr_2nd[:1,:2]

array([[ 5, 10]])

In [8]:
arr_2nd[:2,1:2]

array([[10],
       [25]])

In [9]:
arr_2nd[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [11]:
arr = np.arange(1,11)

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [14]:
arr = arr[arr >5]

In [15]:
arr

array([ 6,  7,  8,  9, 10])

In [16]:
arr = np.arange(1,11)

In [18]:
arr = arr[arr < 3]

In [19]:
arr

array([1, 2])

In [20]:
arr_2nd = np.arange(50)

In [21]:
arr_2nd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
len(arr_2nd)

50

In [24]:
arr_2nd = arr_2nd.reshape(5,10)

In [25]:
arr = np.arange(50).reshape(5,10)

In [26]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
len(arr)

5

In [29]:
arr.shape

(5, 10)

In [31]:
arr[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [32]:
arr = np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr1 = np.arange(10,20)

In [42]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
arr1.shape

(10,)

In [44]:
arr + arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
1/arr1

array([0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [48]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [49]:
np.max(arr)

9

In [50]:
arr.max()

9

In [53]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [55]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [56]:
np.log(arr)

<ipython-input-56-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])