In [2]:
import numpy as np
import math
farenheit = np.array([0,-10,-5,-15,0])

In [3]:
celcius = (farenheit - 31) * (5/9)

In [5]:
celcius > -20

array([ True, False, False, False,  True])

In [6]:
A = np.array([[1,2], [0,1]])
B = np.array([[2,0], [3,4]])

In [7]:
print(A*B)

[[2 0]
 [0 4]]


In [10]:
print(A@B)

[[8 8]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [12]:
 array1 = np.array([[1,2,3], [4,5,6]])

In [13]:
print(array1.shape)

(2, 3)


In [14]:
print(array1.dtype)

int64


In [15]:
array2 = np.array([[7.1,8.2,9.1], [10.4,11.2,12.3]])

In [16]:
print(array2)

[[ 7.1  8.2  9.1]
 [10.4 11.2 12.3]]


In [17]:
print(array2.dtype)

float64


In [19]:
array3 = array1 + array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [20]:
print(array3.sum())

79.3


In [21]:
print(array3.max())

18.3


In [23]:
print(array3.min())

8.1


In [24]:
print(array3.max())

18.3


In [25]:
print(array3.mean())

13.216666666666667


In [26]:
b = np.arange(1,16,1).reshape(3,5)

In [27]:
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
from PIL import Image

In [30]:
from IPython.display import display


In [31]:
a = np.array([1,3,5,7])

In [32]:
a

array([1, 3, 5, 7])

In [33]:
a[]2

SyntaxError: invalid syntax (<ipython-input-33-6c2a189aa618>, line 1)

In [34]:
a[2]

5

In [35]:
a = np.array([[1,2],[3,4], [5,6]])

In [36]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
a[0,1]

2

In [40]:
np.array([a[0,0], a[1,1], a[2,1]])

array([1, 4, 6])

In [44]:
print(a[[0,1,2], [0,1,1]])

[1 4 6]


In [45]:
np.array(a[[0,1,2],[0,1,1]])

array([1, 4, 6])