In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np


In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
zeros(2,5_)

SyntaxError: invalid decimal literal (<ipython-input-4-c8fbb7ca7e3c>, line 1)

In [5]:
zeros(2,5)


NameError: name 'zeros' is not defined

In [6]:
my__list = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my__list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))
# two brackets in the array means the result is a matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(0,11,2)
# 2 means the space between each number

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [15]:
np.linspace(1,5,20)
# 20 means the number of evenly space numbers between 1 and 5
# one bracket in the array means that the result is a vector

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [16]:
np.eyes(4)

AttributeError: module 'numpy' has no attribute 'eyes'

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.13244571, 0.23028295])

In [20]:
np.random.randn(2)

array([-0.94762961,  1.73724989])

In [21]:
np.random.randint(1,100)

42

In [22]:
np.random.randint(1,100,10)

array([38, 63, 41, 66, 41, 41, 67, 65, 53, 28])

In [23]:
arr = np.arange(20)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
arra = np.random.randint(1,100,10)

In [27]:
arra

array([75, 99, 40, 41, 71, 64,  9, 58, 63, 94])

In [28]:
arra.min()

9

In [29]:
arra.max()

99

In [30]:
arra.argmax()

1

In [31]:
arra.argmin()

6

In [33]:
arra.shape

(10,)

In [37]:
arra  = arra.reshape(2,5)

In [38]:
arra.shape

(2, 5)

In [42]:
# instead of using np.random.randint(1,10)
# you can first write from numpy.random import randint
# then randint(1,10)

In [43]:
from numpy.random import randint

In [44]:
randint(1,10)

1

In [45]:
randint(1,10)

8