In [1]:
# np.array(), np.arange(),np.zeros(), np.ones(), np.eye(), np.linespace(),np.random.rand(), np.random.randint(),
# .reshape(), .shape, .min(), .max(), .argmin(), .argmax(), .dtype(), .copy() 

import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# only integers
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(4)

array([0.97981183, 0.26808469, 0.11087919, 0.11654131])

In [20]:
np.random.rand(2,4)

array([[0.25584025, 0.20998181, 0.97274001, 0.86898884],
       [0.94805381, 0.80955616, 0.03273746, 0.04332041]])

In [22]:
np.random.randint(1,3)

2

In [26]:
# a random integer between 0 and 4, including 0 and 4
np.random.randint(0,4)

3

In [27]:
# 10 random integer numbers between 0 and 20

In [28]:
np.random.randint(0,20,10)

array([14,  0, 19, 14, 12,  8, 10,  2,  7, 14])

In [31]:
arr = np.arange(0,24) #include 0 but exclude 24

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
randarr = np.random.randint(0,50,10)

In [35]:
randarr

array([ 8, 49, 26, 46,  8,  0, 38, 27, 30, 46])

In [36]:
len(randarr)

10

In [38]:
randarr.reshape(5,2)


array([[ 8, 49],
       [26, 46],
       [ 8,  0],
       [38, 27],
       [30, 46]])

In [39]:
randarr.max()

49

In [40]:
randarr.min()

0

In [41]:
randarr.argmax()

1

In [42]:
randarr.argmin()

5

In [43]:
arr.shape

(24,)

In [44]:
randarr.shape

(10,)

In [45]:
randarr = randarr.reshape(5,2)

In [47]:
randarr.shape

(5, 2)

In [49]:
randarr.dtype

dtype('int64')

In [50]:
arr.dtype

dtype('int64')

In [53]:
mylist = list(range(0,20,2))

In [54]:
mylist

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [55]:
slice_list = mylist[1:4]

In [57]:
slice_list[:]

[2, 4, 6]

In [58]:
slice_list[0] = 90

In [59]:
slice_list

[90, 4, 6]

In [60]:
mylist

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [61]:
arr = np.arange(0,10,2)

In [62]:
arr

array([0, 2, 4, 6, 8])

In [63]:
slice_arr = arr[2:]

In [64]:
slice_arr

array([4, 6, 8])

In [65]:
slice_arr[:] = 99

In [66]:
slice_arr

array([99, 99, 99])

In [67]:
arr

array([ 0,  2, 99, 99, 99])

In [68]:
arr_copy = arr.copy()

In [69]:
arr_copy[:]=100

In [70]:
arr_copy

array([100, 100, 100, 100, 100])